### ISSUE TITLE
Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by smarigowda** [srivaths/jmeter-driver#1] opened 2015-03-09 10:50 UTC
I tried running driver shell script.

`./driver.sh -s jmxfile.jmx -d data-dir -n 8`

I am getting following error. Could you please help.

`santosh@santosh-vb:~/SAN/jmeterCloud/jmeter-driver$ ./driver.sh -s test_google.jmx -d data-dir -n 1
./driver.sh: 34: ./driver.sh: Syntax error: "(" unexpected
santosh@santosh-vb:~/SAN/jmeterCloud/jmeter-driver$`

**Comment by srivaths** [comment] 2015-03-09 14:27
That's odd.  I just ran your use case without a hitch.
Are you sure you are running the current version of jmeter-driver?  I am asking this because there is no parenthesis on line 34 of driver.sh. 
Grasping at straws....what shell variant are you using (zsh, ksh, bash etc)?

Sri

**Comment by srivaths** [comment] 2015-03-18 12:19
I take it that a older version was being used and the problem is no longer reproducible.

Closing.

**Closed as completed by srivaths** 2015-03-18 12:19 UTC
